version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex
      - run: mix deps.get
      - run: mix espec
